FROM python:3.13

WORKDIR /app
# 필수 패키지 설치
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools wheel build 

ENV PYTHONPATH="/usr/local/lib/python3.13/site-packages:$PYTHONPATH"

COPY requirements-git.txt .
RUN pip install -r requirements-git.txt

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
